#index:
#    path: /
#    controller: App\Controller\DefaultController::index


api_login_check:
    path: /api/login
    methods: POST
    #controller: App\Controller\LoginController:execute

index:
    path: /
    controller: App\Controller\DefaultController:execute
    methods: ['GET']