#index:
#    path: /
#    controller: App\Controller\DefaultController::index


api_login_check:
    path: /api/login
    methods: POST
    #controller: App\Controller\LoginController:execute

api_register:
    path: /api/register
    methods: POST
    controller: App\Controller\RegisterController:execute


index:
    path: /
    controller: App\Controller\DefaultController:execute
    methods: ['GET']